// Petits textes propres à l'interface de la semaine 1 qui n'existent pas encore dans content/fr-CA/interface.json.
// À déplacer dans content/ à la prochaine passe sur les textes (la règle du dépôt : le code n'écrit pas de phrases).
export const S = {
  'panel.more': 'Tout voir',
  'panel.less': 'Replier',
  'panel.date': '{date}',
  'app.title': 'La lisière rallumée',

  'fil.reason.none': 'Elle arrive en tête de ta liste.',
  'fil.reason.start': 'C’est ta quête du moment. Pas besoin de tout régler aujourd’hui.',
  'fil.pause': 'Pause',
  'fil.doing.since': 'En cours depuis {n} min',
  'fil.doing.now': 'En cours',
  'fil.next_step': 'Prochaine étape : {etape}',
  'fil.empty.title': 'Aucune quête ouverte',
  'fil.empty.text': 'L’Orée veille. Ajoute une vraie tâche quand elle se présente.',

  'reason.priority': 'prioritaire',
  'reason.short': 'courte',
  'reason.easy': 'facile',
  'reason.due.today': 'due aujourd’hui',
  'reason.due.tomorrow': 'due demain',
  'reason.due.days': 'due dans {n} jours',
  'reason.passed': 'en attente depuis un moment',
  'reason.old': 'ancienne',

  'late.since': 'Attend depuis {n} j',
  'late.since.today': 'Attend depuis hier',
  'deadline.none': 'Aucune échéance',
  'done.at': 'Faite à {heure}',
  'done.on': 'Faite le {date}',
  'archived.on': 'Archivée le {date}',

  'readonly.tag': 'Lecture seule',
  'readonly.reason': 'Cette quête n’a pas d’identifiant fiable (absent ou en double dans la liste) : elle est en lecture seule.',

  'alt.expand': 'Voir',
  'list.title': 'Toutes les quêtes',
  'list.open.one': '{n} ouverte',
  'list.open.other': '{n} ouvertes',
  'list.done.one': '{n} faite',
  'list.done.other': '{n} faites',
  'list.archived.one': '{n} archivée',
  'list.archived.other': '{n} archivées',
  'filter.sectors': 'Secteurs',
  'filter.quick_group': 'Filtres rapides',
  'filter.clear_all': 'Retirer les filtres',
  'empty.filter.some': 'Essaie un autre filtre, ou retire-les pour tout revoir.',
  'sort.courtes': 'Courtes d’abord',
  'sort.faciles': 'Faciles d’abord',
  'sort.anciennes': 'Plus anciennes',
  'sort.recentes': 'Plus récentes',
  'sort.priorite': 'Priorité',
  'sort.echeance': 'Échéance',

  'add.title': 'Nouvelle quête',
  'add.what': 'Quoi faire ?',
  'add.hint': 'Le secteur se devine à partir des mots du titre.',
  'add.sector': 'Secteur',
  'add.guess': 'Deviné d’après « {mot} »',
  'add.adjust': 'Ajuster',
  'add.summary.prio': 'Priorité',
  'add.summary.effort': 'effort',
  'add.submit': 'Ajouter la quête',
  'add.error.empty': 'Écris d’abord ce qu’il y a à faire.',
  'add.done_today': 'Déjà faite aujourd’hui',
  'add.done_today.hint': 'Elle compte, sans passer par la liste.',
  'add.close': 'Fermer',
  'add.sector.other': 'Autre',

  'hint.prio.high': 'Prioritaire',
  'hint.prio.mid': 'Moyenne',
  'hint.prio.low': 'Basse',
  'hint.effort.high': 'Exigeant',
  'hint.effort.mid': 'Moyen',
  'hint.effort.low': 'Facile',
  'step.dec.priority': 'Diminuer la priorité',
  'step.inc.priority': 'Augmenter la priorité',
  'step.dec.length': 'Diminuer la durée',
  'step.inc.length': 'Augmenter la durée',
  'step.dec.difficulty': 'Diminuer l’effort',
  'step.inc.difficulty': 'Augmenter l’effort',

  'fiche.title': 'Fiche de quête',
  'fiche.close': 'Fermer',
  'fiche.deadline.hint': 'Facultative. Une échéance proche fait monter la Cote.',
  'fiche.steps': 'Étapes',
  'fiche.steps.new': 'Nouvelle étape',
  'fiche.steps.add': 'Ajouter l’étape',
  'fiche.steps.remove': 'Retirer l’étape « {etape} »',
  'fiche.notes.placeholder': 'Un mot pour plus tard',
  'fiche.undo.disabled.late': 'Possible seulement dans les 24 h qui suivent la quête.',
  'fiche.undo.disabled.zero': 'Cette quête n’a rien rapporté : il n’y a rien à remballer.',
  'fiche.readonly': 'Lecture seule : ce que tu changerais ici ne pourrait pas être enregistré de façon sûre.',
  'fiche.occurrence': 'Occurrence {n}',

  'why.note': 'La Cote décide seulement de l’ordre des quêtes. Elle ne change pas ce qu’une quête rapporte.',
  'why.sheet.title': 'Pourquoi la Cote {cote} ?',
  'why.total': 'Cote',

  'announce.none': 'Déjà comptée · aucun nouveau gain',
  'announce.undo': 'Remballée · gains repris',
  'announce.lueur_to': 'Lueur → {secteur}',
  'sr.undone.gains': 'Gains repris : {liste}.',
  'sr.added': 'Quête ajoutée : {quete}.',
  'sr.archived': 'Quête archivée : {quete}.',
  'sr.unarchived': 'Quête sortie des archives : {quete}.',
  'sr.deleted': 'Quête supprimée : {quete}.',
  'sr.reopened': 'Quête réactivée : {quete}.',
  'sr.paused': 'Quête en pause : {quete}.',
  'sr.synced': 'Tout est enregistré.',

  'sync.saving': 'Enregistrement…',
  'sync.saved': 'Enregistré à {heure}',
  'sync.offline.title': 'Hors ligne',
  'sync.error.title': 'Pas encore enregistré sur le serveur',
  'sync.error.busy': 'Le serveur est occupé. Nouvel essai en cours, rien n’est perdu.',
  'sync.fatal.tasks_missing': 'Le fichier des tâches est introuvable sur le serveur. Rien n’a été écrit.',
  'sync.fatal.tasks_unreadable': 'Le fichier des tâches est momentanément illisible. Rien n’a été écrit.',
  'sync.fatal.auth_not_configured': 'Le serveur n’est pas configuré pour recevoir des changements. Rien n’a été écrit.',
  'sync.fatal.title': 'Le serveur ne peut pas enregistrer',

  'token.title': 'Accès à tes quêtes',
  'token.text': 'Le serveur demande un jeton d’accès. Il reste sur cet appareil et ne s’affiche plus ensuite.',
  'token.label': 'Jeton d’accès',
  'token.save': 'Enregistrer le jeton',
  'token.bad': 'Ce jeton n’a pas été accepté. Vérifie-le et réessaie.',

  'load.fail.title': 'Impossible de charger tes quêtes',
  'load.fail.text': 'Rien n’est perdu : réessaie dans un instant.',
  'load.retry': 'Réessayer',

  'confirm.remballer.title': 'Remballer cette quête ?',
  'confirm.close': 'Fermer',
  'res.help.title': 'À quoi sert {nom} ?',
  'notice.dismiss': 'Fermer ce message',
  'notice.dropped': 'Un changement n’a pas pu être appliqué : {raison}',
  'notice.duplicate': 'Ce gain était déjà inscrit : rien n’a été compté en double.',
  'notice.conflict': 'L’Orée a bougé ailleurs. La dernière version est rechargée.',
};
